      const menu = [
        {
          title: "Sautéed Brixham Squid",
          subtitle: "Starter • 478 kcal",
          description:
            "Fresh squid with nduja, sourdough, and squid ink aioli.",
          image: "images/squid.jpeg",
          ingredients: [
            "Brixham squid",
            "Nduja",
            "Sourdough",
            "Squid ink aioli",
          ],
          price: "£7.50",
          category: "starters",
        },
        {
          title: "Cauliflower and Vegan Feta Fritters",
          subtitle: "Starter (vg) • 628 kcal",
          description: "Crispy fritters with Hurfa sweet chilli sauce.",
          image: "images/fritters.jpeg",
          ingredients: ["Cauliflower", "Vegan feta", "Hurfa sweet chilli"],
          price: "£9.00",
          category: "starters",
        },
        {
          title: "Grilled Tenderstem Broccoli",
          subtitle: "Starter (vg) • 356 kcal",
          description: "With romesco sauce and smoked almonds.",
          image: "images/broccoli.jpeg",
          ingredients: [
            "Tenderstem broccoli",
            "Romesco sauce",
            "Smoked almonds",
          ],
          price: "£7.00",
          category: "starters",
        },
        {
          title: "Fried Buttermilk Chicken Wings",
          subtitle: "Starter • 679 kcal",
          description: "Crispy wings with hot honey sauce.",
          image: "images/wings.jpeg",
          ingredients: ["Buttermilk chicken wings", "Hot honey sauce"],
          price: "£8.00",
          category: "starters",
        },
        {
          title: "Glazed Chicken Skewers",
          subtitle: "Starter • 370 kcal",
          description: "With miso, lime and tarragon mayo.",
          image: "images/skewers.jpeg",
          ingredients: [
            "Chicken skewers",
            "Miso glaze",
            "Lime",
            "Tarragon mayo",
          ],
          price: "£7.00",
          category: "starters",
        },
        {
          title: "Grilled Corn",
          subtitle: "Starter • 187 kcal",
          description: "Pico de Gallo with Isle of Wight tomato salsa.",
          image: "images/corn.jpeg",
          ingredients: [
            "Grilled corn",
            "Pico de Gallo",
            "Isle of Wight tomato salsa",
          ],
          price: "£4.00",
          category: "starters",
        },
        {
          title: "Naughty Tots",
          subtitle: "Starter • 771 kcal",
          description:
            "Pulled chicken thigh, pico de gallo, chicken gravy, melted cheese, crispy shallots, hot honey mayo.",
          image: "images/tots.jpeg",
          ingredients: [
            "Pulled chicken thigh",
            "Pico de gallo",
            "Chicken gravy",
            "Melted cheese",
            "Crispy shallots",
            "Hot honey mayo",
          ],
          price: "£8.00",
          category: "starters",
        },
        {
          title: "Triple Cooked Chips",
          subtitle: "Starter • 673 kcal",
          description: "Our signature crispy chips.",
          image: "images/chips.jpeg",
          ingredients: ["Triple cooked chips"],
          price: "£4.50",
          category: "starters",
        },
        {
          title: "Flat Iron Chicken",
          subtitle: "Main • 1729 kcal",
          description: "Hassleback jersey royals with pickled fennel salad.",
          image: "images/flatiron.jpeg",
          ingredients: [
            "Flat iron chicken",
            "Hassleback jersey royals",
            "Pickled fennel salad",
          ],
          price: "£18.00",
          category: "mains",
        },
        {
          title: "Cyder Battered Haddock & Triple Cooked Chips",
          subtitle: "Main • 735 kcal",
          description:
            "Marrowfat peas, curry sauce, tartar sauce, charred lemon.",
          image: "images/fishandchips.jpeg",
          ingredients: [
            "Cyder battered haddock",
            "Triple cooked chips",
            "Marrowfat peas",
            "Curry sauce",
            "Tartar sauce",
            "Charred lemon",
          ],
          price: "£19.50",
          category: "mains",
        },
        {
          title: "Buttermilk Chicken Thigh Burger",
          subtitle: "Main • 1112 kcal",
          description:
            "Crispy maple cured bacon, honey hot sauce mayo, fennel and lime slaw, fries.",
          image: "images/chickenburger.jpeg",
          ingredients: [
            "Buttermilk chicken thigh",
            "Crispy maple cured bacon",
            "Honey hot sauce mayo",
            "Fennel and lime slaw",
            "Fries",
          ],
          price: "£16.00",
          category: "mains",
        },
        {
          title: "Clapham North Signature Burger",
          subtitle: "Main • 946 kcal",
          description:
            "Burger cheese, pickled onions, gherkin, burger sauce, fries.",
          image: "images/beefburger.jpeg",
          ingredients: [
            "Beef patty",
            "Burger cheese",
            "Pickled onions",
            "Gherkin",
            "Burger sauce",
            "Fries",
          ],
          price: "£17.50",
          category: "mains",
        },
        {
          title: "Plant Burger",
          subtitle: "Main (vg) • 667 kcal",
          description:
            "Vegan cheddar, pickled onions, gherkin, burger sauce, fries.",
          image: "images/plant.jpeg",
          ingredients: [
            "Plant-based patty",
            "Vegan cheddar",
            "Pickled onions",
            "Gherkin",
            "Burger sauce",
            "Fries",
          ],
          price: "£16.50",
          category: "mains",
        },
        {
          title: "Rump Steak",
          subtitle: "Main • 1230 kcal",
          description:
            "Bone marrow and wild garlic crumb, Madeira sauce, fries.",
          image: "images/steak.jpeg",
          ingredients: [
            "Rump steak",
            "Bone marrow",
            "Wild garlic crumb",
            "Madeira sauce",
            "Fries",
          ],
          price: "£19.00",
          category: "mains",
        },
        {
          title: "Banana Split",
          subtitle: "Pudding (vg) • 463 kcal",
          description: "Salted caramel ice cream with chocolate chip cookies.",
          image: "images/banana.jpeg",
          ingredients: [
            "Banana",
            "Salted caramel ice cream",
            "Chocolate chip cookies",
          ],
          price: "£6.00",
          category: "puddings",
        },
        {
          title: "Honey Roasted Peach",
          subtitle: "Pudding • 415 kcal",
          description: "Whipped mascarpone with macerated raspberries.",
          image: "images/peach.jpeg",
          ingredients: [
            "Honey roasted peach",
            "Whipped mascarpone",
            "Macerated raspberries",
          ],
          price: "£6.00",
          category: "puddings",
        },
        {
          title: "Strawberry & Basil Cheesecake",
          subtitle: "Pudding • 802 kcal",
          description: "Classic cheesecake with strawberry and basil.",
          image: "",
          ingredients: ["Cheesecake", "Strawberry", "Basil"],
          price: "£6.00",
          category: "puddings",
        },
        {
          title: "Ice Cream Scoop",
          subtitle: "Pudding • 358 kcal",
          description: "Single scoop of premium ice cream.",
          image: "",
          ingredients: ["Premium ice cream"],
          price: "£2.50",
          category: "puddings",
        },
        {
          title: "Sunday Roast",
          subtitle: "Sunday Roast",
          description: "Sunday Roast served with all the trimmings.",
          image: "images/roast.jpeg",
          ingredients: [
            "Potatos, Carrots, Red Cabbage, Creamy Leeks, Yorkshire Pudding, Gravy",
          ],
          price: "£0.00",
          category: "Sunday Roast",
        },
      ];